apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wbuzy2vql-python
  janus-idp.io/tekton: wbuzy2vql-python
  backstage.io/kubernetes-id: wbuzy2vql-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wbuzy2vql-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
